Реализует форму редактирования
htmlacademy-ecmascript/1343593-big-trip-14 pull request #10
Opened 2021-05-04 14:50 UTC by manakhova

2021-05-04 20:15 UTC, obzhorash requested changes
1. оферы на точке подсвечены только выбранные, 
![image](https://user-images.githubusercontent.com/30758444/117063729-e4482900-ad2d-11eb-9cd6-e343220f1d9a.png)
![image](https://user-images.githubusercontent.com/30758444/117063748-ed38fa80-ad2d-11eb-9cfc-b6b4c6f06264.png)
![image](https://user-images.githubusercontent.com/30758444/117063769-f6c26280-ad2d-11eb-85b3-e8f9ba28a191.png)
2. при клике на event после обновление проиходит пересортировка 
![image](https://user-images.githubusercontent.com/30758444/117063991-3f7a1b80-ad2e-11eb-88c0-5464fa05a04c.png)

2021-05-04 20:15 UTC, obzhorash commented on src/view/event-edit.js
> +      // то тз нужно будет загружать офферы с сервера, пока перемешиваю какие есть
офферы будут загружены при старте приложения, надо лишь выбрать нужные из полученных, стоит это предусмотреть(иметь ввиду)

2021-05-08 19:23 UTC, manakhova commented
Есть проблема с перерисовкой офферов при изменении типа маршрута - сам массив перемешивается, но перерисовки не происходит. Не нашла, где ошибка

2021-05-08 21:28 UTC, obzhorash commented
![image](https://user-images.githubusercontent.com/30758444/117553951-3bffd080-b05d-11eb-8857-177cc844259b.png)

Посмотри что делает функция parseEventToData

2021-05-09 18:21 UTC, merged